---
name: Lint

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions: {}

jobs:
  super-linter:
    name: super-linter
    runs-on: ubuntu-latest

    permissions:
      # contents permission to clone the repository
      contents: read
      packages: read
      # issues and pull-requests permissions to write results as pull
      # request comments. Omit them if you don't need summary comments
      issues: write
      pull-requests: write
      # To report GitHub Actions status checks. Omit if you don't need
      # to update commit status
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7 # zizmor: ignore[unpinned-uses]
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter/slim@v8 # zizmor: ignore[unpinned-uses]
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CSS_PRETTIER: false
          VALIDATE_CSS: false
          VALIDATE_GO_MODULES: false
          VALIDATE_GO: false
          VALIDATE_HTML_PRETTIER: false
          VALIDATE_HTML: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_JSCPD: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_JSON: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_MARKDOWN: false # FIXME
          VALIDATE_NATURAL_LANGUAGE: false # FIXME

  staticcheck:
    name: staticcheck
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v7 # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@9716614d4101e79b4340dd97b10e54d68234e431 # v1.4.1
        with:
          version: "2026.2.1"
          build-tags: browser
